name: update html
on:
  push:
    branches: ['master']
    paths:
      - html/**
jobs:
  convert:
    name: Run osm map converter
    runs-on: ubuntu-latest
    steps:
      - name: Copy html
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: cd /home/osm/dev/osmmapsconverter/html && git pull && cp -r *  /var/www/maps
